### ISSUE TITLE
LIBDBUSMENU-GLIB-WARNING

### ISSUE THREAD

**Issue by MVoz** [probonopd/avahi-indicator#2]
uname -a
Linux ubuntu 4.2.0-35-lowlatency #40-Ubuntu SMP PREEMPT Tue Mar 15 23:25:22 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

> avahi-indicator.py:25: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
>   from gi.repository import Gtk, GLib
> avahi-indicator.py:26: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
>   from gi.repository import AppIndicator3 as appindicator
> avahi-indicator.py:39: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
>   from gi.repository import Notify
> Browsing domain 'local' on -1.-1 ...
> Browsing for services of type '_workstation._tcp' in domain 'local' on 3.1 ...
> Browsing for services of type '_workstation._tcp' in domain 'local' on 2.1 ...
> Browsing for services of type '_workstation._tcp' in domain 'local' on 3.0 ...
> Browsing for services of type '_workstation._tcp' in domain 'local' on 2.0 ...
> Found service 'ubuntu [c4:46:19:1c:7b:e8]' of type '_workstation._tcp' in domain 'local' on 3.1.
> Found service 'ubuntu [20:6a:8a:05:86:03]' of type '_workstation._tcp' in domain 'local' on 2.1.
> Found service 'ubuntu [c4:46:19:1c:7b:e8]' of type '_workstation._tcp' in domain 'local' on 2.1.
> Found service 'ubuntu [c4:46:19:1c:7b:e8]' of type '_workstation._tcp' in domain 'local' on 3.0.
> Service data for service 'ubuntu [c4:46:19:1c:7b:e8]' of type '_workstation._tcp' in domain 'local' on 3.1:
>   Host ubuntu.local (fe80::c646:19ff:fe1c:7be8), port 9, TXT data: []
>   0.00083175 secs since launch
> Found service 'ubuntu [20:6a:8a:05:86:03]' of type '_workstation._tcp' in domain 'local' on 2.0.
> Service data for service 'ubuntu [20:6a:8a:05:86:03]' of type '_workstation._tcp' in domain 'local' on 2.1:
>   Host ubuntu.local (fe80::c646:19ff:fe1c:7be8), port 9, TXT data: []
>   0.0008895 secs since launch
> Service data for service 'ubuntu [c4:46:19:1c:7b:e8]' of type '_workstation._tcp' in domain 'local' on 2.1:
>   Host ubuntu.local (fe80::c646:19ff:fe1c:7be8), port 9, TXT data: []
>   0.0009014 secs since launch
> Service data for service 'ubuntu [c4:46:19:1c:7b:e8]' of type '_workstation._tcp' in domain 'local' on 3.0:
>   Host ubuntu.local (192.168.0.3), port 9, TXT data: []
>   0.0009095 secs since launch
> Service data for service 'ubuntu [20:6a:8a:05:86:03]' of type '_workstation._tcp' in domain 'local' on 2.0:
>   Host ubuntu.local (192.168.0.2), port 9, TXT data: []
>   0.000917916666667 secs since launch
> (avahi-indicator.py:7903): LIBDBUSMENU-GLIB-WARNING **: About to Show called on an item wihtout submenus.  We're ignoring it.
> 
> (avahi-indicator.py:7903): LIBDBUSMENU-GLIB-WARNING **: About to Show called on an item wihtout submenus.  We're ignoring it.
> 
> (avahi-indicator.py:7903): LIBDBUSMENU-GLIB-WARNING **: About to Show called on an item wihtout submenus.  We're ignoring it.
> 
> (avahi-indicator.py:7903): LIBDBUSMENU-GLIB-WARNING **: About to Show called on an item wihtout submenus.  We're ignoring it.

сам индикатор текстовый, надпись Avahi, меню выпадает, но без надписей, пустой листинг
не как у вас на скриншоте

**Comment by probonopd** [comment]
Sorry I do not know the solution. Which version of Ubuntu are you using?

**Comment by MVoz** [comment]
Ubuntu 15.10

**Comment by MVoz** [comment]
нашел как исправить некоторые моменты

> import re
> import os, sys
> import urllib2
> import signal
> import gi
> gi.require_version('Gtk', '3.0')
> from gi.repository import Gtk, GLib
> import gi
> gi.require_version('AppIndicator3', '0.1')
> from gi.repository import AppIndicator3 as appindicator
> 
> import avahi, gettext, gobject, dbus, avahi.ServiceTypeDatabase
> import gi
> gi.require_version('Notify', '0.7')

но с иконкой и меню, не решено

**Comment by probonopd** [comment]
Я не говорю на русском , но вы говорите, что он работает для вас сейчас ?
